# Credits to https://github.com/renanlecaro

name: Deploy Meteor App to Server
on:
  push:
    branches-ignore: 
      - p/*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: cd ./app && npm ci

      - name: Check formatting
        run: cd ./app && npm run ci:formatting

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: cd ./app && npm ci

      - name: Install Meteor
        run: curl https://install.meteor.com/ | sh

      - name: Run Unit Tests
        run: cd ./app && npm run ci:test

      - name: Run e2e tests
        run: cd ./app && npm run ci:test:e2e

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_rsa_github_actor

      # Test SSH connectivity (fail fast)
      - name: Test ssh key to fail fast
        run: ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} -i ~/.ssh/id_rsa_github_actor -t "pwd"

      - uses: actions/checkout@v4

      - name: Get production dependencies only
        run: cd ./app && npm ci --omit=dev

      - name: (Hack) Remove malformed package
        run: find ./app/node_modules -name malformed_package_json -type d -prune -exec rm -rf "{}" \;

      - name: Install meteor
        run: curl https://install.meteor.com/ | sh

      - name: Bundle the app and upload to Hoster
        run: cd ./deploy && npm i && npx mup deploy
        env:
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_HOST: ${{ vars.SSH_HOST }}
          DOMAIN: ${{ vars.DOMAIN }}
          PROXY_PORT: ${{ vars.PROXY_PORT }}
